### ISSUE TITLE
Which Ports needed to get synced?

### ISSUE THREAD

**Issue by Marow** [dubaicoin-dbix/go-dubaicoin#5]
Hi, i am using Ubuntu Server and want to know, which Ports are needed to get synced?

Most time, i get now around 7 Peers in over 48 Hours. Think thats not a much...
Which Ports must allowed in Firewall to get enaugh peers?

I have already disabled firewall for testings... but also nothing comes in... 0 Peers after waiting much time

**Comment by slaeya** [comment]
Project seems somewhat abandonded

**Comment by youssefelallali** [comment]
Hi @Marow you need to activate this ports:

P2PPort: 57955
RPCPort: 7565
WSPort: 7557
